import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Title, Subtitle } from "../components/essential/text";
import { CustomButton } from "../components/essential/buttons";
import { IoArrowForward } from "react-icons/io5";
import { BgImg } from "../components/bgImg";
import { Navbar } from "../components/composed/navbar";
export default function Home() {
  const router = useRouter();
  const urlRoute = router.pathname;
  return (
    <React.Fragment>
      <Head>
        <title>Verb Tenses</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar active={urlRoute} />
      <main className="main">
        <Title>
          Verb tenses <br /> Understandable by anyone
        </Title>
        <button
          className="components__essential--button"
          onClick={() => {
            router.push("/select");
          }}
        >
          Ver mas
          <IoArrowForward stroke="#eeeeee" />
        </button>
        <BgImg src="/london.webp" nextPage={false} />
      </main>
    </React.Fragment>
  );
}
